
name: CI

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull and Run Skin Trader Backend
        run: | 
            docker login https://docker.pkg.github.com -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
            docker run -p 8000:8000 docker.pkg.github.com/kevinab168/skin_trader/skin_trader_backend:main          
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
  
  push_to_registry:
    needs: cypress-run
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kevinab168/skin_trader_frontend/skin_trader_frontend
          tag_with_ref: true
