
name: CI

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to Docker 
        run: |
          docker login https://docker.pkg.github.com -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker run -d -p 80:8000 docker.pkg.github.com/kevinab168/skin_trader/skin_trader_backend:main
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve 
          config-file: cypress.json
          
  push_to_registry:
    needs: cypress-run
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kevinab168/skin_trader_frontend/skin_trader_frontend
          tag_with_ref: true
  deploy:
    needs: push_to_registry
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "docker-compose.yml"
        target: "~"
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~
          docker-compose down
          docker image prune
          docker login https://docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose pull docker pull docker.pkg.github.com/kevinab168/skin_trader_frontend/skin_trader_frontend:main
          docker-compose up -d --build